# ------------------------------------
# RemoteRedstone v4.0 Configuration
# ------------------------------------

# Webサーバーが使用するポート番号
web-port: 8080

# --- ログイン機能の設定 ---
login:
  # ログイン機能を有効にするか (true / false)
  # trueに設定すると、Web UIにアクセスする際にユーザー名とパスワードが要求されます。
  enabled: true

  # ログインに使用するユーザー名
  username: admin

  # ログインに使用するパスワード
  # ★★★★★ 必ずデフォルトから変更してください！ ★★★★★
  password: changeme