name: RemoteRedstone
version: Var0.1-BATE
main: com.example.remoteredstone.RemoteRedstone
author: Ayuruka
description: Remotely controls redstone blocks via a configurable web interface with login.

permissions:
  remoteredstone.use:
    description: Allows using debug commands.
    default: op